annotations:
  fips: "true"
  images: |
    - name: kubectl
      version: 1.35.1
      image: registry-1.docker.io/bitnami/kubectl:latest
    - name: os-shell
      version: "5"
      image: registry-1.docker.io/bitnami/os-shell:latest
    - name: redis
      version: 8.6.0
      image: registry-1.docker.io/bitnami/redis:latest
    - name: redis-exporter
      version: 1.81.0
      image: registry-1.docker.io/bitnami/redis-exporter:latest
    - name: redis-sentinel
      version: 8.6.0
      image: registry-1.docker.io/bitnami/redis-sentinel:latest
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.6.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.36.0
description: "Redis(R) is an open source, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets."
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: "Broadcom, Inc. All Rights Reserved."
  url: https://github.com/bitnami/charts
name: redis
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/redis
version: 25.3.0
